-- SECURITY HARDENING MIGRATION
-- Generated by Antigravity
-- Run this in Supabase SQL Editor

-- 1. Enable 'admin' role in user_profiles
ALTER TABLE user_profiles DROP CONSTRAINT user_profiles_role_check;
ALTER TABLE user_profiles ADD CONSTRAINT user_profiles_role_check 
    CHECK (role IN ('player', 'coach', 'admin'));

-- 2. Set Admin User (Alex Lewis)
-- Using the email addresses found in App.jsx as admin candidates
UPDATE user_profiles 
SET role = 'admin' 
WHERE email IN ('alex.lewis@rra.internal', 'alex.lewis@rramelbourne.com');

-- 3. Enable RLS on all un-enabled tables
ALTER TABLE assessment_domains ENABLE ROW LEVEL SECURITY;
ALTER TABLE domain_weights ENABLE ROW LEVEL SECURITY;
ALTER TABLE competition_tiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE eligibility_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE vmcu_associations ENABLE ROW LEVEL SECURITY;
ALTER TABLE vccl_regions ENABLE ROW LEVEL SECURITY;
ALTER TABLE association_competitions ENABLE ROW LEVEL SECURITY;
-- ensure others are enabled too (idempotent)
ALTER TABLE applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE players ENABLE ROW LEVEL SECURITY;
ALTER TABLE competition_grades ENABLE ROW LEVEL SECURITY;
ALTER TABLE coach_assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE engine_constants ENABLE ROW LEVEL SECURITY;
ALTER TABLE stat_benchmarks ENABLE ROW LEVEL SECURITY;
ALTER TABLE stat_domain_weights ENABLE ROW LEVEL SECURITY;
ALTER TABLE stat_sub_weights ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE program_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE analytics_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE squad_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE squad_allocations ENABLE ROW LEVEL SECURITY;
ALTER TABLE skill_definitions ENABLE ROW LEVEL SECURITY;

-- 4. Helper Function for Admin Check (Performance Oriented)
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM user_profiles
    WHERE id = auth.uid() AND role = 'admin'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 5. Helper Function for Coach Check
CREATE OR REPLACE FUNCTION public.is_coach()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM user_profiles
    WHERE id = auth.uid() AND role = 'coach'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 6. Clean up existing permissive policies
DROP POLICY IF EXISTS "Allow anon insert" ON applications;
DROP POLICY IF EXISTS "Allow public insert coach assessments" ON coach_assessments;
DROP POLICY IF EXISTS "Allow public update coach assessments" ON coach_assessments;
DROP POLICY IF EXISTS "Allow public upsert coach assessments" ON coach_assessments;
DROP POLICY IF EXISTS "Allow public delete competition grades" ON competition_grades;
DROP POLICY IF EXISTS "Allow public insert competition grades" ON competition_grades;
DROP POLICY IF EXISTS "Allow public insert players" ON players;
DROP POLICY IF EXISTS "Allow public update players" ON players;
-- Drop inefficient policies (to be replaced)
DROP POLICY IF EXISTS "Users read own profile" ON user_profiles;
DROP POLICY IF EXISTS "Users update own profile" ON user_profiles;
DROP POLICY IF EXISTS "Users insert own profile" ON user_profiles;
DROP POLICY IF EXISTS "coaches_read_members" ON program_members;
DROP POLICY IF EXISTS "members_read_own" ON program_members;
DROP POLICY IF EXISTS "admin_read_analytics" ON analytics_events;
DROP POLICY IF EXISTS "users_insert_own_analytics" ON analytics_events;
DROP POLICY IF EXISTS "admin_manage_squad_groups" ON squad_groups;
DROP POLICY IF EXISTS "admin_manage_squad_allocations" ON squad_allocations;


-- 7. Define New Policies

-- A. Reference Data (Read-only for all Authenticated, Write for Admin)
-- Tables: assessment_domains, domain_weights, competition_tiers, eligibility_rules, vmcu_associations, vccl_regions, association_competitions, engine_constants, stat_benchmarks, stat_domain_weights, stat_sub_weights, skill_definitions

DO $$
DECLARE
    tbl text;
BEGIN
    FOR tbl IN 
        SELECT tablename FROM pg_tables 
        WHERE schemaname = 'public' 
        AND tablename IN ('assessment_domains', 'domain_weights', 'competition_tiers', 'eligibility_rules', 'vmcu_associations', 'vccl_regions', 'association_competitions', 'engine_constants', 'stat_benchmarks', 'stat_domain_weights', 'stat_sub_weights', 'skill_definitions')
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS "Enable read access for authenticated users" ON %I', tbl);
        EXECUTE format('CREATE POLICY "Enable read access for authenticated users" ON %I FOR SELECT TO authenticated USING (true)', tbl);
        
        EXECUTE format('DROP POLICY IF EXISTS "Enable write access for admins" ON %I', tbl);
        EXECUTE format('CREATE POLICY "Enable write access for admins" ON %I FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin())', tbl);
    END LOOP;
END $$;


-- B. User Profiles
-- Admin: Full Access
-- Users: Read Own Only (No Update, per user request "Admin Only Changes")
CREATE POLICY "Admin manage all profiles" ON user_profiles
    FOR ALL TO authenticated
    USING (public.is_admin())
    WITH CHECK (public.is_admin());

CREATE POLICY "Users read own profile" ON user_profiles
    FOR SELECT TO authenticated
    USING (auth.uid() = id);

-- C. Players Table
-- Admin: Full Access
-- Coach: Read All (to see roster) - but CANNOT EDIT
-- Player: Read Own. Update Own (Self Assessment only).
CREATE POLICY "Admin manage all players" ON players
    FOR ALL TO authenticated
    USING (public.is_admin())
    WITH CHECK (public.is_admin());

CREATE POLICY "Coaches read all players" ON players
    FOR SELECT TO authenticated
    USING (public.is_coach());

CREATE POLICY "Players read own data" ON players
    FOR SELECT TO authenticated
    USING (auth.uid() = auth_user_id);

-- Trigger to prevent Players from updating non-assessment fields
CREATE OR REPLACE FUNCTION check_player_update_permissions()
RETURNS TRIGGER AS $$
BEGIN
  -- If user is admin, allow everything (handled by RLS mainly, but good safety)
  IF public.is_admin() THEN
    RETURN NEW;
  END IF;

  -- If user is updating their own record
  IF auth.uid() = OLD.auth_user_id THEN
    -- Prevent changing core fields
    IF (NEW.name IS DISTINCT FROM OLD.name) OR
       (NEW.role IS DISTINCT FROM OLD.role) OR
       (NEW.club IS DISTINCT FROM OLD.club) OR
       (NEW.association IS DISTINCT FROM OLD.association) OR
       (NEW.dob IS DISTINCT FROM OLD.dob) OR
       (NEW.email IS DISTINCT FROM OLD.email) THEN
        RAISE EXCEPTION 'Players cannot edit core profile details (Name, Role, Club, DOB, Email). Contact Admin.';
    END IF;
    -- Allowed: self_ratings, voice_answers, goals, injury, phone, parent_details
    RETURN NEW;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_player_update_permission ON players;
CREATE TRIGGER trg_player_update_permission
BEFORE UPDATE ON players
FOR EACH ROW EXECUTE FUNCTION check_player_update_permissions();

-- Allow players to update their own row (trigger restricts columns)
CREATE POLICY "Players update own data" ON players
    FOR UPDATE TO authenticated
    USING (auth.uid() = auth_user_id)
    WITH CHECK (auth.uid() = auth_user_id);


-- D. Coach Assessments
-- Admin: Full Access
-- Coach: Create/Update/Delete where they are the coach/allocator
-- Player: Read Own
CREATE POLICY "Admin manage assessments" ON coach_assessments
    FOR ALL TO authenticated
    USING (public.is_admin())
    WITH CHECK (public.is_admin());

CREATE POLICY "Coaches manage own assessments" ON coach_assessments
    FOR ALL TO authenticated
    USING (auth.uid() = coach_id OR auth.uid() = allocated_by)
    WITH CHECK (auth.uid() = coach_id OR auth.uid() = allocated_by);

CREATE POLICY "Players read own assessments" ON coach_assessments
    FOR SELECT TO authenticated
    USING (exists (select 1 from players where players.id = coach_assessments.player_id and players.auth_user_id = auth.uid()));


-- E. Competition Grades (History)
-- Admin: Full Access
-- Player: Read Own
-- Coach: Read All (via Player association?) -> Coach needs to see player history.
CREATE POLICY "Admin manage comp grades" ON competition_grades
    FOR ALL TO authenticated
    USING (public.is_admin())
    WITH CHECK (public.is_admin());

CREATE POLICY "Read comp grades" ON competition_grades
    FOR SELECT TO authenticated
    USING (
        -- Admin/Coach can read all (Coach needs to see history of any player)
        public.is_admin() OR public.is_coach() OR 
        -- Player reads own
        exists (select 1 from players where players.id = competition_grades.player_id and players.auth_user_id = auth.uid())
    );


-- F. Program Members & Squads
-- Admin: Full Access
CREATE POLICY "Admin manage program members" ON program_members
    FOR ALL TO authenticated
    USING (public.is_admin())
    WITH CHECK (public.is_admin());

CREATE POLICY "Admin manage squad groups" ON squad_groups
    FOR ALL TO authenticated
    USING (public.is_admin())
    WITH CHECK (public.is_admin());

CREATE POLICY "Admin manage squad allocations" ON squad_allocations
    FOR ALL TO authenticated
    USING (public.is_admin())
    WITH CHECK (public.is_admin());

-- Coaches Read Members/Squads? (Likely needed for dashboard roster)
CREATE POLICY "Coaches read program members" ON program_members
    FOR SELECT TO authenticated
    USING (public.is_coach());

CREATE POLICY "Coaches read squad groups" ON squad_groups
    FOR SELECT TO authenticated
    USING (public.is_coach());

CREATE POLICY "Coaches read squad allocations" ON squad_allocations
    FOR SELECT TO authenticated
    USING (public.is_coach());


-- G. Analytics
-- Admin: Read All
-- Users: Insert Own
CREATE POLICY "Admin read all analytics" ON analytics_events
    FOR SELECT TO authenticated
    USING (public.is_admin());

CREATE POLICY "Users insert own analytics" ON analytics_events
    FOR INSERT TO authenticated
    WITH CHECK (auth.uid() = user_id);

-- 8. Applications Table (Public Insert is actually OK for signups? Assuming 'applications' prevents unauthorized play)
-- Assuming 'applications' is for incoming non-authenticated users?
-- If users are NOT authenticated, RLS applies to 'anon'.
-- Existing policy was "Allow anon insert". This is probably fine if it's a signup form.
-- But we should restrict Update/Delete.
DROP POLICY IF EXISTS "Anon insert applications" ON applications;
CREATE POLICY "Anon insert applications" ON applications
    FOR INSERT TO anon
    WITH CHECK (true);

CREATE POLICY "Admin manage applications" ON applications
    FOR ALL TO authenticated
    USING (public.is_admin())
    WITH CHECK (public.is_admin());
